# 🏥 Oumi Model Hospital - Treatment Recipe
# Generated: 2025-12-12T21:57:53.284077
# Recipe ID: hallucination_high_20251212_215753
# Description: High hallucination rate with moderate skill degradation
#
# Usage: oumi train hallucination_high_20251212_215753.yaml

_recipe_metadata:
  recipe_id: hallucination_high_20251212_215753
  version: '1.0'
  author: oumi-hospital
  symptom: hallucination
  severity: HIGH
  skill_verdict: caution
  description: High hallucination rate with moderate skill degradation
model:
  model_name: mistral-7b-unsafe
  trust_remote_code: true
  torch_dtype_str: bfloat16
data:
  train:
    datasets:
    - dataset_name: text_sft_jsonl
      dataset_path: cure_dataset_hallucination.jsonl
training:
  trainer_type: TRL_SFT
  output_dir: ./healed_models/hallucination_high_20251212_215753
  learning_rate: 7.500000000000001e-05
  num_train_epochs: 2
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  optimizer: adamw_torch
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  save_steps: 500
  eval_strategy: steps
  eval_steps: 500
peft:
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  lora_task_type: CAUSAL_LM
