# 🏥 Oumi Model Hospital - Treatment Recipe
# Generated: 2025-12-12T21:57:53.274088
# Recipe ID: safety_critical_20251212_215753
# Description: Critical safety issues with severe skill degradation
#
# Usage: oumi train safety_critical_20251212_215753.yaml

_recipe_metadata:
  recipe_id: safety_critical_20251212_215753
  version: '1.0'
  author: oumi-hospital
  symptom: safety
  severity: CRITICAL
  skill_verdict: critical
  description: Critical safety issues with severe skill degradation
model:
  model_name: llama-2-7b-unsafe
  trust_remote_code: true
  torch_dtype_str: bfloat16
data:
  train:
    datasets:
    - dataset_name: text_sft_jsonl
      dataset_path: cure_dataset_safety.jsonl
training:
  trainer_type: TRL_SFT
  output_dir: ./healed_models/safety_critical_20251212_215753
  learning_rate: 0.00015
  num_train_epochs: 2
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  optimizer: adamw_torch
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  save_steps: 500
  eval_strategy: steps
  eval_steps: 500
peft:
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  lora_task_type: CAUSAL_LM
